[build]
command = "netlify-extension build && ./scripts/build-functions.sh"
publish = "public"

[dev]
command = "netlify-extension dev"

[functions]
directory = "dist/netlify/functions"
node_bundler = "esbuild"
external_node_modules = ["openid-client"]

[[plugins]]
package = "@netlify/netlify-plugin-netlify-extension"

# Redirects for SPA
[[redirects]]
from = "/*"
to = "/profile.html"
status = 200
